"""A bridged agent's client for the shared memory.

Cerebro, Perestroika, Melocotón and Wattson keep their own runtimes; this is how
they read and write the store the coding sessions read. It is a single file with
no dependency but `httpx`, because it is **copied into those repositories** by
`agents export-client` rather than installed: none of them should have to take
FastAPI, Alembic and pgvector as dependencies to write one memory.

Two rules it is built around.

**A bridge never breaks because the store is down.** Every method has a value it
returns when the platform is unreachable — an empty brief, no hits, `None` — and
logs what happened. An agent that stops answering ops because a memory service
is restarting is worse than an agent that answers without the extra context.

**A bridge is its own identity.** It authenticates with its own Authentik M2M
client, and everything it writes is attributed to `m2m:<name>` by the server,
which is why nothing here can name an author.

    memory = MemoryClient.from_env("cerebro")
    if memory:
        system_prompt = memory.brief() + "\\n\\n" + system_prompt
        memory.remember("El mandato de Alza se pide antes de la evaluación")

The async twin is the same API with `await`, for a runtime that has an event
loop to protect.
"""

# Generated by `agents export-client` from src/ruuf_agents/client/memory_client.py in ruufsolar/gru.
# Do not edit here: change it there and re-export, or the two drift and the
# bug is found twice.

from __future__ import annotations

import logging
import os
import time
from dataclasses import dataclass
from typing import Any

import httpx

logger = logging.getLogger(__name__)

DEFAULT_TOKEN_URL = "https://auth.ruuf.solar/application/o/token/"
TIMEOUT_SECONDS = 10.0
REFRESH_MARGIN_SECONDS = 60.0
"""Re-mint a minute early, so no request rides a token that expires in flight."""


@dataclass(frozen=True)
class Brief:
    """What an agent knows, and the version of it.

    `memory_clock` is what makes a brief citable: a bridge that records which
    prompt produced an answer can record which memory did too, and two runs with
    the same clock read the same store.
    """

    text: str
    memory_clock: int = 0

    def __bool__(self) -> bool:
        return bool(self.text)


@dataclass(frozen=True)
class Memory:
    """One row, as much of it as a bridge has any use for."""

    id: str
    content: str
    tier: str
    kind: str
    topic: str | None
    source_ref: str | None
    author: str | None

    @classmethod
    def of(cls, body: dict[str, Any]) -> Memory:
        return cls(
            id=str(body.get("id", "")),
            content=str(body.get("content", "")),
            tier=str(body.get("tier", "")),
            kind=str(body.get("kind", "")),
            topic=body.get("topic"),
            source_ref=body.get("source_ref"),
            author=body.get("author"),
        )


@dataclass
class Credentials:
    """Where the platform is and who this agent is to it.

    RUUF_AGENTS_URL                 https://<fqdn>
    RUUF_AGENTS_M2M_CLIENT_ID       this agent's Authentik client
    RUUF_AGENTS_M2M_CLIENT_SECRET
    RUUF_AGENTS_TOKEN_URL           optional, defaults to Authentik's
    RUUF_AGENTS_TOKEN               a personal access token instead of the two
                                    above, for trying things from a laptop
    """

    base_url: str
    client_id: str = ""
    client_secret: str = ""
    token_url: str = DEFAULT_TOKEN_URL
    static_token: str = ""

    @classmethod
    def from_env(cls, env: dict[str, str] | None = None) -> Credentials | None:
        source = env if env is not None else dict(os.environ)
        base_url = (source.get("RUUF_AGENTS_URL") or "").strip().rstrip("/")
        if not base_url:
            return None
        client_id = (source.get("RUUF_AGENTS_M2M_CLIENT_ID") or "").strip()
        client_secret = (source.get("RUUF_AGENTS_M2M_CLIENT_SECRET") or "").strip()
        static_token = (source.get("RUUF_AGENTS_TOKEN") or "").strip()
        if not static_token and not (client_id and client_secret):
            # Half a credential is no credential, and a bridge that silently
            # writes nowhere is the failure this returns None to avoid.
            logger.warning(
                "RUUF_AGENTS_URL is set but neither RUUF_AGENTS_TOKEN nor a complete "
                "RUUF_AGENTS_M2M_CLIENT_ID / _SECRET pair is; the shared memory is off"
            )
            return None
        return cls(
            base_url=base_url,
            client_id=client_id,
            client_secret=client_secret,
            token_url=(source.get("RUUF_AGENTS_TOKEN_URL") or DEFAULT_TOKEN_URL).strip(),
            static_token=static_token,
        )


@dataclass
class _Token:
    value: str = ""
    expires_at: float = 0.0

    def valid(self) -> bool:
        return bool(self.value) and time.monotonic() < self.expires_at - REFRESH_MARGIN_SECONDS


class MemoryClient:
    """The synchronous client. Blocking calls, one per turn at most."""

    def __init__(
        self,
        agent: str,
        credentials: Credentials,
        *,
        client: httpx.Client | None = None,
    ) -> None:
        self.agent = agent
        self.credentials = credentials
        self._client = client or httpx.Client(timeout=TIMEOUT_SECONDS)
        self._token = _Token()

    @classmethod
    def from_env(
        cls, agent: str, *, env: dict[str, str] | None = None, client: httpx.Client | None = None
    ) -> MemoryClient | None:
        """The client, or `None` when this deployment has no shared memory
        configured — which is what a bridge checks before using it."""
        credentials = Credentials.from_env(env)
        if credentials is None:
            return None
        return cls(agent, credentials, client=client)

    # --- the three calls -----------------------------------------------------

    def brief(self, *, token_budget: int = 6000) -> str:
        """Everything this agent knows, for the top of its system prompt.

        Stable on purpose: the same bytes until a memory changes, so a provider
        that caches prompt prefixes keeps hitting the cache.
        """
        return self.brief_detail(token_budget=token_budget).text

    def brief_detail(self, *, token_budget: int = 6000) -> Brief:
        """The brief and its memory clock, for a runtime that records which
        knowledge produced an answer."""
        body = self._get(f"/api/agents/{self.agent}/brief", {"token_budget": token_budget})
        return _brief_from(body)

    def recall(self, query: str, *, limit: int = 5, mode: str = "hybrid") -> list[Memory]:
        """Search this agent's memory and the collective memory."""
        body = self._post(
            f"/api/agents/{self.agent}/recall",
            {"query": query, "limit": limit, "mode": mode},
        )
        if body is None:
            return []
        return [Memory.of(hit["memory"]) for hit in body.get("hits", []) if hit.get("memory")]

    def remember(
        self,
        content: str,
        *,
        kind: str = "fact",
        topic: str | None = None,
        source_ref: str | None = None,
        upsert: bool = False,
    ) -> Memory | None:
        """Store one learning in short-term memory.

        With `upsert`, `source_ref` becomes an idempotency key: pass the id of
        the row in this agent's own database and re-syncing it supersedes what
        was there rather than adding a second copy. That is how a bridge syncs a
        table it keeps editing.
        """
        body = self._post(
            f"/api/agents/{self.agent}/memories",
            {
                "content": content,
                "kind": kind,
                "topic": topic,
                "source_ref": source_ref,
                "upsert": upsert,
            },
        )
        return Memory.of(body) if body is not None else None

    # --- plumbing ------------------------------------------------------------

    def _get(self, path: str, params: dict[str, Any]) -> dict[str, Any] | None:
        return self._request("GET", path, params=params)

    def _post(self, path: str, json: dict[str, Any]) -> dict[str, Any] | None:
        return self._request("POST", path, json=json)

    def _request(self, method: str, path: str, **kwargs: Any) -> dict[str, Any] | None:
        token = self._bearer()
        if token is None:
            return None
        try:
            response = self._client.request(
                method,
                self.credentials.base_url + path,
                headers={"Authorization": f"Bearer {token}"},
                **kwargs,
            )
        except httpx.HTTPError as exc:
            logger.warning("shared memory unreachable (%s %s): %s", method, path, exc)
            return None
        if response.status_code == 401:
            # The token was rejected: forget it, so the next call re-mints rather
            # than repeating a refusal for the rest of the token's lifetime.
            self._token = _Token()
        if response.status_code >= 400:
            logger.warning("shared memory refused %s %s: %s", method, path, response.status_code)
            return None
        return response.json()

    def _bearer(self) -> str | None:
        if self.credentials.static_token:
            return self.credentials.static_token
        if self._token.valid():
            return self._token.value
        try:
            response = self._client.post(
                self.credentials.token_url,
                data={
                    "grant_type": "client_credentials",
                    "client_id": self.credentials.client_id,
                    "client_secret": self.credentials.client_secret,
                },
            )
            response.raise_for_status()
        except httpx.HTTPError as exc:
            logger.warning("could not mint an M2M token: %s", exc)
            return None
        self._token = _token_from(response.json())
        return self._token.value or None


class AsyncMemoryClient:
    """The same client for a runtime with an event loop to protect."""

    def __init__(
        self,
        agent: str,
        credentials: Credentials,
        *,
        client: httpx.AsyncClient | None = None,
    ) -> None:
        self.agent = agent
        self.credentials = credentials
        self._client = client or httpx.AsyncClient(timeout=TIMEOUT_SECONDS)
        self._token = _Token()

    @classmethod
    def from_env(
        cls,
        agent: str,
        *,
        env: dict[str, str] | None = None,
        client: httpx.AsyncClient | None = None,
    ) -> AsyncMemoryClient | None:
        credentials = Credentials.from_env(env)
        if credentials is None:
            return None
        return cls(agent, credentials, client=client)

    async def brief(self, *, token_budget: int = 6000) -> str:
        return (await self.brief_detail(token_budget=token_budget)).text

    async def brief_detail(self, *, token_budget: int = 6000) -> Brief:
        body = await self._request(
            "GET", f"/api/agents/{self.agent}/brief", params={"token_budget": token_budget}
        )
        return _brief_from(body)

    async def recall(self, query: str, *, limit: int = 5, mode: str = "hybrid") -> list[Memory]:
        body = await self._request(
            "POST",
            f"/api/agents/{self.agent}/recall",
            json={"query": query, "limit": limit, "mode": mode},
        )
        if body is None:
            return []
        return [Memory.of(hit["memory"]) for hit in body.get("hits", []) if hit.get("memory")]

    async def remember(
        self,
        content: str,
        *,
        kind: str = "fact",
        topic: str | None = None,
        source_ref: str | None = None,
        upsert: bool = False,
    ) -> Memory | None:
        body = await self._request(
            "POST",
            f"/api/agents/{self.agent}/memories",
            json={
                "content": content,
                "kind": kind,
                "topic": topic,
                "source_ref": source_ref,
                "upsert": upsert,
            },
        )
        return Memory.of(body) if body is not None else None

    async def _request(self, method: str, path: str, **kwargs: Any) -> dict[str, Any] | None:
        token = await self._bearer()
        if token is None:
            return None
        try:
            response = await self._client.request(
                method,
                self.credentials.base_url + path,
                headers={"Authorization": f"Bearer {token}"},
                **kwargs,
            )
        except httpx.HTTPError as exc:
            logger.warning("shared memory unreachable (%s %s): %s", method, path, exc)
            return None
        if response.status_code == 401:
            self._token = _Token()
        if response.status_code >= 400:
            logger.warning("shared memory refused %s %s: %s", method, path, response.status_code)
            return None
        return response.json()

    async def _bearer(self) -> str | None:
        if self.credentials.static_token:
            return self.credentials.static_token
        if self._token.valid():
            return self._token.value
        try:
            response = await self._client.post(
                self.credentials.token_url,
                data={
                    "grant_type": "client_credentials",
                    "client_id": self.credentials.client_id,
                    "client_secret": self.credentials.client_secret,
                },
            )
            response.raise_for_status()
        except httpx.HTTPError as exc:
            logger.warning("could not mint an M2M token: %s", exc)
            return None
        self._token = _token_from(response.json())
        return self._token.value or None


def _brief_from(body: dict[str, Any] | None) -> Brief:
    """An unreachable platform is an empty brief, not an exception: a bridge that
    stops answering because a memory service is restarting is worse than one that
    answers with less context."""
    if body is None:
        return Brief(text="")
    blocks = [str(body.get("stable") or ""), str(body.get("volatile") or "")]
    return Brief(
        text="\n\n".join(block for block in blocks if block),
        memory_clock=int(body.get("memory_clock") or 0),
    )


def _token_from(body: dict[str, Any]) -> _Token:
    value = str(body.get("access_token") or "")
    # Authentik always sends expires_in; a provider that does not gets a short,
    # safe window rather than a token cached forever.
    expires_in = float(body.get("expires_in") or 300)
    return _Token(value=value, expires_at=time.monotonic() + expires_in)
